name: publish-book

# Only run this when the master branch changes
on:
  workflow_dispatch:
  release:
    types: [published]
    # If your git repository has the Jupyter Book within some-subfolder next to
    # unrelated files, you can make this run only if a file within that specific
    # folder has been modified.
    #
    # paths:
    # - some-subfolder/**

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Install dependencies
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Build the book
    - name: Build the book
      run: |
        DATE=$(date +'%d %B %Y')
        sed -i "s/Version: .*$/Version: ${{  github.ref_name }} ($DATE)/" _config_publish.yml
        jupyter-book build . --config _config_publish.yml --toc _toc_publish.yml
      env:
        TROVE_API_KEY: ${{ secrets.TROVE_API_KEY }}
    
    - name: rsync deployments
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --delete
        path: ./_build/html/
        remote_path: /var/www/html/
        remote_host: tdg.glamworkbench.cloud.edu.au
        remote_user: github
        remote_key: ${{ secrets.DEPLOY_KEY }}
